/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './*.html',
    './src/**/*.{html,js,css}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        surface2: 'var(--surface2)',
        border: 'var(--border)',
        text: 'var(--text)',
        muted: 'var(--muted)',
        hdr: 'var(--hdr)',
        'hdr-text': 'var(--hdr-text)',
        'hdr-muted': 'var(--hdr-muted)',
        'badge-bg': 'var(--badge-bg)',
        'badge-brd': 'var(--badge-brd)',
        'sop-bg': 'var(--sop-bg)',
        'btn-bg': 'var(--btn-bg)',
        'btn-hov': 'var(--btn-hov)',
        'btn-brd': 'var(--btn-brd)',
        'tl-track': 'var(--tl-track)',
        'tl-border': 'var(--tl-border)',
        'now-line': 'var(--now-line)',
        'tip-bg': 'var(--tip-bg)',
        'tip-brd': 'var(--tip-brd)',
        'tip-text': 'var(--tip-text)',
        accent: 'var(--accent)',
        ok: 'var(--ok)',
        warn: 'var(--warn)',
        risk: 'var(--risk)',
        pending: 'var(--pending)',
        fabric: 'var(--fabric)',
        paint: 'var(--paint)',
        texture: 'var(--texture)',
        milestone: 'var(--milestone)',
      },
      fontFamily: {
        sans: ['"Encode Sans"', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
